version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-server:
    build: .
    ports:
      - "3000-3010:3000"
    environment:
      - PORT=3000
    depends_on: #Wait for depends go on
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abc
      - MONGO_INITDB_ROOT_PASSWORD=abc
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
